pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "aishu2194/simple-node-app"
        DOCKER_TAG = "latest"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/Aishwaryareddy2194/project-ci-cd-pipe.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'cd simple-nodejs && docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-credential',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $DOCKER_IMAGE:$DOCKER_TAG'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh 'docker stop simple-node-app || true'
                sh 'docker rm simple-node-app || true'
                sh 'docker run -d -p 5000:5000 --name simple-node-app $DOCKER_IMAGE:$DOCKER_TAG'
            }
        }
    }
}
